server.port: 8000


spring:
  application:
    name: users
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mysql://root:root@${DB_URL:localhost}/users?useSsl=false
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
hibernate:
  format_sql: true
  ddl-auto: update
